wandb_version: 1

alpha:
  desc: null
  value: 0.0001
average:
  desc: null
  value: false
class_weight:
  desc: null
  value: null
early_stopping:
  desc: null
  value: false
epsilon:
  desc: null
  value: 0.1
eta0:
  desc: null
  value: 0.0
fit_intercept:
  desc: null
  value: true
l1_ratio:
  desc: null
  value: 0.15
learning_rate:
  desc: null
  value: optimal
loss:
  desc: null
  value: log_loss
max_iter:
  desc: null
  value: 1000
n_iter_no_change:
  desc: null
  value: 5
n_jobs:
  desc: null
  value: null
penalty:
  desc: null
  value: l2
power_t:
  desc: null
  value: 0.5
random_state:
  desc: null
  value: null
shuffle:
  desc: null
  value: true
tol:
  desc: null
  value: 0.001
validation_fraction:
  desc: null
  value: 0.1
verbose:
  desc: null
  value: 0
warm_start:
  desc: null
  value: false
_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.6
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712543249.0
    t:
      1:
      - 5
      - 6
      - 7
      - 8
      - 53
      - 54
      - 55
      - 105
      2:
      - 5
      - 6
      - 7
      - 8
      - 53
      - 54
      - 55
      - 105
      3:
      - 2
      - 16
      - 23
      4: 3.11.5
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      10:
      - 5
      13: windows-amd64
    viz:
      class_proportions:
        id: wandb/class_proportions/v1
        historyFieldSettings:
          x-axis: _step
          key: class_proportions
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
      roc:
        id: wandb/roc/v1
        historyFieldSettings:
          x-axis: _step
          key: roc
      precision_recall:
        id: wandb/pr_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: precision_recall
      feature_importances:
        id: wandb/feature_importances/v1
        historyFieldSettings:
          x-axis: _step
          key: feature_importances
test_size:
  desc: null
  value: 0.2
train_len:
  desc: null
  value: 455
test_len:
  desc: null
  value: 114
