wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.6
    framework: lightgbm
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1712541422.0
    t:
      1:
      - 5
      - 6
      - 7
      - 8
      - 53
      - 54
      - 55
      - 105
      2:
      - 5
      - 6
      - 7
      - 8
      - 53
      - 54
      - 55
      - 105
      3:
      - 23
      4: 3.11.5
      5: 0.16.6
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
    viz:
      summary_metrics:
        id: wandb/metrics/v1
        historyFieldSettings:
          x-axis: _step
          key: summary_metrics
      learning_curve:
        id: wandb/learning_curve/v1
        historyFieldSettings:
          x-axis: _step
          key: learning_curve
      outlier_candidates:
        id: wandb/outliers/v1
        historyFieldSettings:
          x-axis: _step
          key: outlier_candidates
      residuals:
        id: wandb/residuals_plot/v1
        historyFieldSettings:
          x-axis: _step
          key: residuals
